### PR TITLE
Update input.v5.js

### PR DESCRIPTION
**Pull request by knicklabs**
Set latitude using correct property in the geometry location object.

### CODE REVIEW

**Comment by ethanclevenger91** [comment]
Google changes these letters all the time - better to use the Google Maps `lat()` and `lng()` functions. See #3

**Comment by chrisgoddard** [comment]
Thanks! Haven't maintained this in a while.

**Comment by ethanclevenger91** [comment]
Just to reiterate - Google changes these letters _all the time_ and this solution will eventually break as well. See #3

**Comment by maltekebbel** [comment]
I also have a problem with the coordinates. When i search for something in the google map field, everything is fine, but the coordinates will not be written, i don t see them ... also when i save the post/page, the map/image is back to the default location. Any Help?

**Pull request merged**
